### ISSUE TITLE
More supported extensions

### ISSUE THREAD

**Issue by GalMrvar** [Ghabki/Download-folder-urejevalnik#2]
i've downloaded script and following files remained in download folder:
- [x]  .tgz 

- [x] .log

- [x] .sql

- [x] .mp3

- [x] .py

- [x] .vsix

- [x] .iso

- [x] .ps

- [x] .diagcab

- [x] .R

- [x] .csv

- [x] .pdf'

- [x] .gz

- [x] .rar

- [x] .svg

**Comment by PremiumG** [comment]
končnice dodance + dodan exception handling.
